### ISSUE TITLE
Smilies & emojis

### ISSUE THREAD

**Issue by nogweii** [vladimir-tikhonov/regexy#2]
A really common use case for regexes I find online is trying to find & replace all of the emojis in a free form text document with images. However, the quality of the regex varies each time, most often running into issues replacing smiley-like text in places it shouldn't be.

For instance, given a series of smiles: `:)`, `:(`, and `:/`. One issue is `:/` and full URLs. The regex shouldn't match on `http://github.com` but many do.

**Comment by vladimir-tikhonov** [comment]
done #7

**Comment by nogweii** [comment]
Very cool, thanks!
