### ISSUE TITLE
Feature request: HostName regex

### ISSUE THREAD

**Issue by take-five** [vladimir-tikhonov/regexy#4]
Hi,

Is it possible to extract hostname regular expression from Regexy::Web::Url into separate class?

**Comment by vladimir-tikhonov** [comment]
For sure, thanks for suggestion :+1:

**Comment by vladimir-tikhonov** [comment]
done #6

**Comment by take-five** [comment]
awesome, thanks! :+1:

**Comment by take-five** [comment]
I've just looked into implementation and it seems that hostname passed as IPv4/6 would be treated as invalid. Is it intentional?

**Comment by vladimir-tikhonov** [comment]
@take-five yes, according the specification ip address is not a valid hostname. If you want to match both hostnames and ip addresses you could use something like `r = Regexy::Web::IPv4.new | Regexy::Web::IPv6.new | Regexy::Web::Hostname.new`

**Comment by vladimir-tikhonov** [comment]
@take-five I thinking of  creating alias for `Regexy::Web::IPv4.new | Regexy::Web::IPv6.new | Regexy::Web::Hostname.new`, something like `WebAddress` or `ServerAddress`, WDYT? I don't want to confuse people who expect `Hostname` regexp to work according RFC.

**Comment by take-five** [comment]
@vladimir-tikhonov, yes, I think alias is a perfect solution
